// <auto-generated />
namespace TutoringCenter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HELPPP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HELPPP));
        
        string IMigrationMetadata.Id
        {
            get { return "201902201639171_HELPPP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
